on:
  issues:
    types: [labeled, unlabeled]
  push:
    paths:
      - '.github/labels.json'

name: Create Default Labels
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'recursive'

      - uses: lannonbr/issue-label-manager-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: true # will delete any labels that aren't in the .github/labels.json (this is set to false by default)

      - name: Load .env file
        uses: xom9ikk/dotenv@v2.1.0
        with:
          path: .github

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.DB_HOST }}"
          echo "Variable 2: ${{ env.DB_USER }}"
          echo "Variable 3: ${{ env.DB_PASS }}"
