on:
  issues:
    types: [labeled, unlabeled]
  push:
    paths:
      - '.github/labels.json'
    
name: Create Default Labels
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: lannonbr/issue-label-manager-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: true # will delete any labels that aren't in the .github/labels.json (this is set to false by default) 
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.VARIABLE_1 }}"
          echo "Variable 2: ${{ env.VARIABLE_2 }}"
          echo "Variable 3: ${{ env.VARIABLE_3 }}"
